<thead>
  <tr>
    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      ลำดับ
    </th>

    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      รหัส GFMIS
    </th>

    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      รหัสครุภัณฑ์
    </th>

    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      ผู้รับผิดชอบ
    </th>

    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      รายการ
    </th>

    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      หน่วย
    </th>

    {/* ยอดคงเหลือตามบัญชี ณ วันเริ่มต้น */}
    <th
      colSpan={2}
      className="
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-1
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      <div className="flex flex-col items-center justify-center leading-tight">
        <span className="whitespace-nowrap text-xs font-extrabold sm:text-xs lg:text-xs">
          ยอดคงเหลือตามบัญชี
        </span>

        <span className="mt-1 whitespace-nowrap text-xs font-extrabold sm:text-xs lg:text-xs">
          ณ วันที่ {formatThaiShortDate(accountStartDate)}
        </span>
      </div>
    </th>

    {/* ยอดคงเหลือตามบัญชี ณ วันสิ้นสุด */}
    <th
      rowSpan={2}
      className="
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-1
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      <div className="flex flex-col items-center justify-center leading-tight">
        <span className="whitespace-nowrap text-xs font-extrabold sm:text-xs lg:text-xs">
          ยอดคงเหลือตามบัญชี
        </span>

        <span className="mt-1 whitespace-nowrap text-xs font-extrabold sm:text-xs lg:text-xs">
          ณ วันที่ {formatThaiShortDate(accountEndDate)}
        </span>
      </div>
    </th>

    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      จำนวนที่ตรวจนับได้
    </th>

    <th
      colSpan={2}
      className="
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-1
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      <div className="flex flex-col items-center justify-center leading-tight">
        <span className="whitespace-nowrap text-xs font-extrabold sm:text-xs lg:text-xs">
          ผลการตรวจนับ
        </span>

        <span className="mt-1 whitespace-nowrap text-xs font-extrabold sm:text-xs lg:text-xs">
          ถูกต้องตรงกับยอดคงเหลือตามบัญชี
        </span>
      </div>
    </th>

    <th
      colSpan={4}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      สภาพครุภัณฑ์ที่ตรวจนับ
    </th>

    <th
      rowSpan={2}
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-2
        text-center
        align-middle
        font-extrabold
        !text-white
      "
    >
      หมายเหตุ
    </th>
  </tr>

  <tr>
    {/* รับ / จ่าย อยู่ใต้หัวกลุ่มยอดคงเหลือตามบัญชีโดยตรง */}
    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-1
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      รับ
    </th>

    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-1
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      จ่าย
    </th>

    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      ถูกต้อง
    </th>

    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      ไม่ถูกต้อง
    </th>

    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      ใช้งาน
    </th>

    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      ชำรุด
    </th>

    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      เสื่อมสภาพ
    </th>

    <th
      className="
        whitespace-nowrap
        border
        border-black
        bg-gradient-to-r
        from-slate-800
        to-slate-700
        px-0.5
        py-1.5
        text-center
        align-middle
        text-xs
        font-extrabold
        !text-white
      "
    >
      ไม่สามารถใช้งาน
    </th>
  </tr>
</thead>